# Generated by Django 4.2.7 on 2023-11-20 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=128)),
                ('tg_username', models.CharField(max_length=64)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.university')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.university')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.university')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsGroupsSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.studentsgroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsGroupsStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
                ('students_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.studentsgroup')),
            ],
        ),
    ]
