# Generated by Django 4.2.7 on 2023-11-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needed_time', models.IntegerField()),
                ('type', models.CharField(choices=[('1', 'Студент ответил на вопрос правильно'), ('2', 'Студент ответил на вопрос неправильно'), ('3', 'Студент пропустил этот вопрос')], max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='question.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='question.test')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='question.answer')),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='statistic.statistic')),
            ],
        ),
    ]
